### PR TITLE
Switch to a pure STM core; remove concur dependency

### PR DESCRIPTION
**Pull request by pkamenarsky**

### CODE REVIEW

**Comment by seagreen** [comment]
Whoa! Would you be willing to give a one sentence motivation for this, and how it's intended to affect app developers?

**Comment by seagreen** [comment]
I'm guessing it will make things a little slower but remove edge case bugs, which sounds awesome.

**Comment by pkamenarsky** [comment]
You're exactly right, the motivation was to remove edge case bugs and finally have a stable core to build on.

The bad news is this approach won't work and is completely and utterly broken and misguided and introduces even more edge case bugs :D Utter madness, this is super tricky to get right.

So *don't* use this commit, I'll have to revert it.

**Comment by seagreen** [comment]
Haha, good to know! I'll wait to upgrade.

**Pull request merged**
